sudo: required

services:
    - docker

before_install:
    - docker build -t srikanth1261/loginapp .

script:
    - docker run srikanth1261/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push srikanth1261/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: docker-loginapp
    env: Docker-loginapp-env-1
    bucket_name: elasticbeanstalk-ap-south-1-673717811715
    bucket_path: docker-loginapp
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
